swagger: '2.0'
info:
  version: "0.1.0"
  title: Gogs API v2 - Admin Endpoints
# security definitions
x-sec:
  $ref: 'https://raw.githubusercontent.com/patrickmcclory/gogs-api-draft/master/sec.yaml#'
securityDefinitions:
  $ref: '#/x-sec/securityDefinitions'
paths:
  /admin/users:
    post:
      responses:
        default:
          $ref: '#/x-resp/Default'
  /admin/users/{username}:
    parameters:
      - $ref: '#/x-params/Username'
    patch:
      responses:
        default:
          $ref: '#/x-resp/Default'
    delete:
      responses:
        default:
          $ref: '#/x-resp/Default'
  /admin/users/{username}/keys:
    parameters:
      - $ref: '#/x-params/Username'
    post:
      responses:
        default:
          $ref: '#/x-resp/Default'
  /admin/users/{username}/orgs:
    parameters:
      - $ref: '#/x-params/Username'
    post:
      responses:
        default:
          $ref: '#/x-resp/Default'
  /admin/users/{username}/repos:
    parameters:
      - $ref: '#/x-params/Username'
    post:
      responses:
        default:
          $ref: '#/x-resp/Default'
  /admin/orgs/{orgname}/teams:
    parameters:
      - $ref: '#/x-params/OrgName'
  /admin/teams/{teamid}/members/{username}:
    parameters:
      - $ref: '#/x-params/TeamID'
      - $ref: '#/x-params/Username'
  /admin/team/{teamid}/repos/{reponame}:
    parameters:
      - $ref: '#/x-params/TeamID'
      - $ref: '#/x-params/Reponame'
    put:
      responses:
        default:
          $ref: '#/x-resp/Default'
    delete:
      responses:
        default:
          description: UnexpectedError
#Common Params
x-params:
  $ref: 'https://raw.githubusercontent.com/patrickmcclory/gogs-api-draft/master/param/common.yaml#'
x-resp:
  $ref: 'https://raw.githubusercontent.com/patrickmcclory/gogs-api-draft/ec470ea587c34b3b56dc6bdd8dcbdc62dfb30ead/resp/common.yaml#'
