x-params:
  $ref: 'https://raw.githubusercontent.com/patrickmcclory/gogs-api-draft/master/param/common.yaml#'
x-resp:
  $ref: 'https://raw.githubusercontent.com/patrickmcclory/gogs-api-draft/master/resp/common.yaml#'
swagger: '2.0'
info:
  version: "0.1.0"
  title: Gogs API v2 - Users Endpoints
# security definitions
x-sec:
  $ref: 'https://raw.githubusercontent.com/patrickmcclory/gogs-api-draft/master/sec.yaml#'
securityDefinitions:
  $ref: '#/x-sec/securityDefinitions'
paths:
  /users/search:
    get:
      responses:
        default:
          $ref: '#/x-resp/Default'
  /users/{username}:
    get:
      responses:
        default:
          $ref: '#/x-resp/Default'
  /users/{username}/orgs:
    parameters:
      - $ref: '#/x-params/Username'
    get:
      responses:
        default:
          $ref: '#/x-resp/Default'
  /users/{username}/tokens:
    parameters:
      - $ref: '#/parameters/Username'
    post:
      security:
        $ref: '#/x-sec/x-model/basicAuth'
      responses:
        default:
          $ref: '#/x-resp/Default'

  /users/{username}/keys:
    parameters:
      - $ref: '#/parameters/Username'
    get:
      security:
        $ref: '#/x-sec/x-model/tokenAuth'
      responses:
        default:
          $ref: '#/x-resp/Default'

  /users/{username}/followers:
    parameters:
      - $ref: '#/parameters/Username'
    get:
      security:
        $ref: '#/x-sec/x-model/tokenAuth'
      responses:
        default:
          $ref: '#/x-resp/Default'
  /users/{username}/following:
    parameters:
      - $ref: '#/parameters/Username'
    get:
      security:
        $ref: '#/x-sec/x-model/tokenAuth'
      responses:
        default:
          $ref: '#/x-resp/Default'
  /users/{username}/following/{target}:
    parameters:
      - $ref: '#/parameters/Username'
      - $ref: '#/parameters/TargetUsername'
    get:
      security:
        $ref: '#/x-sec/x-model/tokenAuth'
      responses:
        default:
          $ref: '#/x-resp/Default'
